apiVersion: v1alpha
kind: cypress
sauce:
  region: eu-central-1
  metadata:
    name: Testing Cypress Support
    tags:
      - e2e
      - release team
      - other tag
    build: Release $CI_COMMIT_SHORT_SHA
cypress:
  version: 5.6.0
  configFile: "cypress.json"  # We determine related files based on the location of the config file.
suites:
  - name: "Cypress Chrome"
    browser: "chrome"
    config:
      testFiles: [ "**/*.*" ] # Cypress native glob support.
