
apiVersion: v1
metadata:
  name: Feature XYZ
  tags:
    - e2e
    - release team
    - other tag
  build: Release $CI_COMMIT_SHORT_SHA
files:
  - ./tests/cypress.spec.js
image:
  base: saucelabs/stt-cypress-mocha-node
  version: v0.1.3
sauce:
  region: us-west-1
